version: '2'

services:
  discordbot.core:
    image: discordbot.core:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ./DiscordBot.Core:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
